# Generated by Django 4.1.5 on 2023-09-07 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 7, 17, 28, 590083, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
